management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always

management.metrics.tags.application=erp-backend

logging.file.name=/app/logs/spring-boot-app.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
spring.output.ansi.enabled=ALWAYS

# Force Spring to initialize the Hikari pool
spring.datasource.hikari.pool-name=MyTestPool
spring.datasource.hikari.register-mbeans=true

# Set a short timeout so you know quickly if it fails
spring.datasource.hikari.initialization-fail-timeout=0
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
