server.servlet.context-path=/api
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always


management.metrics.tags.application=erp-backend


logging.file.name=/app/logs/spring-boot-app.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
spring.output.ansi.enabled=ALWAYS
